title: 南德其中
description: >

baseurl: "/"
theme:

# tipue_search
tipue_search:
  include:
    pages: true
  exclude:
    files: [index.md, search.html, Blog_content.md, DS_AI_ML_content.md, CiscoCert_content.md]